config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    member do
      post :claim
    end
  end
  resources :categories
  resources :scheduled_agendas do
    member do
      post :add_product
      post :remember
      post :score
    end
  end
  resources :products

  #devise config
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
  controllers: { sessions: 'sessions',
                 registrations: 'users/registrations'
                }

  #other routes
  root to: 'statics#home'

  namespace :admin do
    resources :users
  end

  resources :certificates, only: %i(index create show)
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/article_user.rb
class ArticleUser < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :user

  has_many :certificate_products
  has_many :products, through: :certificate_products
end

app/models/certificate_product.rb
class CertificateProduct < ApplicationRecord
  belongs_to :certificate
  belongs_to :product
end

app/models/collect.rb
class Collect < ApplicationRecord
  belongs_to :product
  belongs_to :scheduled_agenda
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :collects
  has_many :scheduled_agendas, through: :collects
  
  belongs_to :category

  has_many :certificate_products
  has_many :certificates, through: :certificate_products
end

app/models/scheduled_agenda.rb
class ScheduledAgenda < ApplicationRecord
  STATE_INITIAL = 'initial'
  STATE_QUALITY = 'quality'

  has_many :collects
  has_many :products, through: :collects

  has_one :scheduled_agenda_score
  belongs_to :owner, class_name: "User", foreign_key: 'owner_id'

  def quality
    ScheduledAgendaScore.where(scheduled_agenda_id: self.id).destroy_all
    total = 0
    self.products.each do |product|
      total = total + product.category.score
      ScheduledAgendaScore.create(
        scheduled_agenda_id: self.id,
        product_id: product.id,
        score: product.category.score,
        rate: product.category.rate,
        total: product.category.score * product.category.rate,
        owner_id: self.owner_id
      )
    end

    user = User.find(self.owner_id)
    user.score = total
    user.save!

    self.state =  ScheduledAgenda::STATE_QUALITY
    self.save!
  end
end

app/models/scheduled_agenda_score.rb
class ScheduledAgendaScore < ApplicationRecord
  belongs_to :scheduled_agenda
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable

  ROLE_ADMIN = 'admin'
  ROLE_USER = 'user'
  ROLE_MANANGER = 'mananger'

  enum role: [ROLE_ADMIN, ROLE_USER, ROLE_MANANGER]

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :name, presence: true

  def admin?
    self.role == ROLE_ADMIN
  end

  def user?
    self.role == ROLE_USER
  end

  def mananger?
    self.role == ROLE_MANANGER
  end
end

app/controllers/scheduled_agendas_controller.rb
class ScheduledAgendasController < ApplicationController
  layout "home"

  before_action :set_scheduled_agenda, only: %i[ show edit update destroy ]

  # GET /scheduled_agendas or /scheduled_agendas.json
  def index
    @scheduled_agendas = ScheduledAgenda.all
  end

  # GET /scheduled_agendas/1 or /scheduled_agendas/1.json
  def show
  end

  # GET /scheduled_agendas/new
  def new
    @scheduled_agenda = ScheduledAgenda.new
  end

  # GET /scheduled_agendas/1/edit
  def edit
  end

  # POST /scheduled_agendas or /scheduled_agendas.json
  def create
    all_params = scheduled_agenda_params
    pp all_params
    all_params [:owner_id] = current_user.id
    @scheduled_agenda = ScheduledAgenda.new(all_params)

    respond_to do |format|
      if @scheduled_agenda.save
        format.html { redirect_to @scheduled_agenda, notice: "Fue agendado correctamente." }
        format.json { render :show, status: :created, location: @scheduled_agenda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @scheduled_agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scheduled_agendas/1 or /scheduled_agendas/1.json
  def update
    respond_to do |format|
      if @scheduled_agenda.update(scheduled_agenda_params)
        format.html { redirect_to @scheduled_agenda, notice: "La cita fue reprogramada correctamente." }
        format.json { render :show, status: :ok, location: @scheduled_agenda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @scheduled_agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scheduled_agendas/1 or /scheduled_agendas/1.json
  def destroy
    @scheduled_agenda.destroy
    respond_to do |format|
      format.html { redirect_to scheduled_agendas_url, notice: "La agena fue eliminada correctamente." }
      format.json { head :no_content }
    end
  end

  def add_product
    scheduled_agenda = ScheduledAgenda.find(params[:id])

    collect = Collect.new(scheduled_agenda_id: scheduled_agenda.id, product_id: params[:collect][:product_id])

    if collect.save
      render json: { collect: collect, product: collect.product }, status: 200
    else
      render json: { errors: collect.errors.messages }, status: 406
    end
  end

  def remember
    ScheludedAgendaMailer.remember(params[:id]).deliver_now
  end

  def score
    scheduled_agenda = ScheduledAgenda.find(params[:id])

    if scheduled_agenda.state == ScheduledAgenda::STATE_QUALITY
      return render json: { errors: 'This one has already been liquidated' }, status: 406
    end
    scheduled_agenda.quality
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scheduled_agenda
      @scheduled_agenda = ScheduledAgenda.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def scheduled_agenda_params
      params.require(:scheduled_agenda).permit(
        :address,
        :contact_name,
        :contact_email,
        :contact_phone_number,
        :scheduled_date
      )
    end

    def collect_params
      params.require(:collect).permit(:product_id)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  layout "home"
  
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/scheduled_agendas_helper.rb
module ScheduledAgendasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/scheduled_agendas/_form.html.erb
<%= form_with(model: scheduled_agenda) do |form| %>
  <% if scheduled_agenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scheduled_agenda.errors.count, "error") %> prohibited this scheduled_agenda from being saved:</h2>

      <ul>
        <% scheduled_agenda.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label 'nombre del contacto' %>
    <%= form.text_field :contact_name %>
  </div>

  <div class="field">
    <%= form.label 'email del contacto' %>
    <%= form.text_field :contact_email %>
  </div>

  <div class="field">
    <%= form.label 'telefono del contacto' %>
    <%= form.text_field :contact_phone_number %>
  </div>

  <div class="field">
    <%= form.label 'fecha de recogida' %>
    <%= form.date_select :scheduled_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scheduled_agendas/edit.html.erb
<h1>Editing Scheduled Agenda</h1>

<%= render 'form', scheduled_agenda: @scheduled_agenda %>

<%= link_to 'Mostrar', @scheduled_agenda %> |
<%= link_to 'Atras', scheduled_agendas_path %>

app/views/scheduled_agendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Agenda cita</h1>

<table>
  <thead>
    <tr>
      <th>Direccion</th>
      <th>nombre del contacto</th>
      <th>email del contacto</th>
      <th>Telefono del contacto</th>
      <th>Fecha de recogida</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scheduled_agendas.each do |scheduled_agenda| %>
      <tr>
        <% if current_user.user?() && current_user.id == scheduled_agenda.owner_id %>
          <td><%= scheduled_agenda.address %></td>
          <td><%= scheduled_agenda.contact_name %></td>
          <td><%= scheduled_agenda.contact_email %></td>
          <td><%= scheduled_agenda.contact_phone_number %></td>
          <td><%= scheduled_agenda.scheduled_date %></td>
          <td><%= link_to 'Mostrar', scheduled_agenda %></td>
          <% if current_user.user?() %>
            <td><%= link_to 'Editar', edit_scheduled_agenda_path(scheduled_agenda) %></td>
            <td><%= link_to 'Eliminar', scheduled_agenda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% else  %>
          <% if current_user.admin?() %>
            <td><%= scheduled_agenda.address %></td>
            <td><%= scheduled_agenda.contact_name %></td>
            <td><%= scheduled_agenda.contact_email %></td>
            <td><%= scheduled_agenda.contact_phone_number %></td>
            <td><%= scheduled_agenda.scheduled_date %></td>
            <td><%= link_to 'Mostrar', scheduled_agenda %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.user?() %>
  <%= link_to 'Nueva agenda', new_scheduled_agenda_path %>
<% end %>

app/views/scheduled_agendas/new.html.erb
<h1>Nueva cita</h1>

<%= render 'form', scheduled_agenda: @scheduled_agenda %>

<%= link_to 'Atras', scheduled_agendas_path %>

app/views/scheduled_agendas/show.html.erb
<p id="notice"><%= notice %></p>
<input style="display: none;" id="scheduled-agenda-id" type="text" value="<%= @scheduled_agenda.id%>" />
<p>
  <strong>Direccion:</strong>
  <%= @scheduled_agenda.address %>
</p>

<p>
  <strong>Nombre del conctacto:</strong>
  <%= @scheduled_agenda.contact_name %>
</p>

<p>
  <strong>Email del contacto:</strong>
  <%= @scheduled_agenda.contact_email %>
</p>

<p>
  <strong>Telefono del contacto:</strong>
  <%= @scheduled_agenda.contact_phone_number %>
</p>

<p>
  <strong>Fecha de recogida:</strong>
  <%= @scheduled_agenda.scheduled_date %>
</p>

<% if current_user.role === User::ROLE_USER %>
  <button class="show-btn">Add product</button>
<% end %>

<% if current_user.role === User::ROLE_ADMIN %>
  <br>
  <br>
  <button id="button-remember">Recordatorio</button>
  <br/>
  <br>
  <button id="button-score">Liquidar</button>
<% end %>
<br/>
<br>
<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Descripcion</th>
      <th>Alto</th>
      <th>Ancho</th>
      <th>Peso</th>
      <th>Observacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="scheduled_date-product-list">
    <% @scheduled_agenda.products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.description %></td>
        <td><%= product.high %></td>
        <td><%= product.width %></td>
        <td><%= product.weight %></td>
        <td><%= product.observation %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
<br>
<%= link_to 'Editar', edit_scheduled_agenda_path(@scheduled_agenda) %> |
<%= link_to 'Atras', scheduled_agendas_path %>

<br/>
<br/>
<%= link_to 'Home', root_path %>



<div id="dialog" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <span id="dialog-close" class="close">&times;</span>
    <p>Some text in the Modal..</p>
      <table>
        <thead>
          <tr>
            <th>Id</th>
            <th>Descripcion</th>
            <th>Adicionar</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody id="product-list">
        </tbody>
      </table>
  </div>
</div>


<script>
  let products = []

  function loadProduct() {
    $.ajax({
      url: '/products',
      type: 'GET',
      dataType: 'json',
      // data: {
      //   format: 'json'
      // },
      success: function(data) {
        products = data.products;
        $.each(data.products, function(i, product) {
          $("#product-list").append('<tr><td>'+product.id+'</td><td>'+product.description+'</td><td><button onclick="button(this)" name="'+product.id+'">add</button></td></tr>');
        });
      },
      error: function(data) {
        console.log("error ", data);
      },
    });
  }

  function addProductOnScheduledAgenda(params) {
    let id =  $('#scheduled-agenda-id').val();
    $.ajax({
      url: '/scheduled_agendas/'+id+'/add_product',
      type: 'POST',
      dataType: 'json',
      data: {
        collect: {
          product_id: params
        }
      },
      success: function(data) {
        console.log("todo ok ", data);
        $("#scheduled_date-product-list").append('<tr><td>'+data.product.id+'</td><td>'+data.product.description+'</td><td>'+data.product.high+'</td><td>'+data.product.width+'</td><td>'+data.product.weight+'</td><td>'+data.product.observation+'</td></tr>');
      },
      error: function(data) {
        console.log("error ", data);
      },
    });
  }

  function rememberScheduledAgenda () {
    $.ajax({
      url: '/scheduled_agendas/'+$('#scheduled-agenda-id').val()+'/remember',
      type: 'POST',
      dataType: 'json',
      success: function(data) {
        console.log("todo ok ", data);
      },
      error: function(data) {
        console.log("error ", data);
      },
    });
  }

  function scoreScheduledAgenda () {
    $.ajax({
      url: '/scheduled_agendas/'+$('#scheduled-agenda-id').val()+'/score',
      type: 'POST',
      dataType: 'json',
      success: function(data) {
        alert("Fue liquidado correctamente al usuario propietarario");
        console.log("todo ok ", data);
      },
      error: function(data) {
        alert("Este agenda ya fue liquidado ");
      },
    });
  }

  $(document).ready(function(){
    loadProduct();
  });

  function button(event) {
    let element = products.find((product, index) => product.id == event.name);
    var formData = new FormData();
    addProductOnScheduledAgenda(element.id);
  }

  $('.show-btn').on('click', function() {
    $('#dialog').show();
  });

  $('#dialog-close').on('click', function() {
    $('#dialog').hide();
  });

  $('#button-remember').on('click', function() {
    rememberScheduledAgenda();
  });

  $('#button-score').on('click', function() {
    scoreScheduledAgenda();
  });
</script>