config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    member do
      post :claim
    end
  end
  resources :categories
  resources :scheduled_agendas do
    member do
      post :add_product
      post :remember
      post :score
    end
  end
  resources :products

  #devise config
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
  controllers: { sessions: 'sessions',
                 registrations: 'users/registrations'
                }

  #other routes
  root to: 'statics#home'

  namespace :admin do
    resources :users
  end

  resources :certificates, only: %i(index create show)
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/article_user.rb
class ArticleUser < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :user

  has_many :certificate_products
  has_many :products, through: :certificate_products
end

app/models/certificate_product.rb
class CertificateProduct < ApplicationRecord
  belongs_to :certificate
  belongs_to :product
end

app/models/collect.rb
class Collect < ApplicationRecord
  belongs_to :product
  belongs_to :scheduled_agenda
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :collects
  has_many :scheduled_agendas, through: :collects
  
  belongs_to :category

  has_many :certificate_products
  has_many :certificates, through: :certificate_products
end

app/models/scheduled_agenda.rb
class ScheduledAgenda < ApplicationRecord
  STATE_INITIAL = 'initial'
  STATE_QUALITY = 'quality'

  has_many :collects
  has_many :products, through: :collects

  has_one :scheduled_agenda_score
  belongs_to :owner, class_name: "User", foreign_key: 'owner_id'

  def quality
    ScheduledAgendaScore.where(scheduled_agenda_id: self.id).destroy_all
    total = 0
    self.products.each do |product|
      total = total + product.category.score
      ScheduledAgendaScore.create(
        scheduled_agenda_id: self.id,
        product_id: product.id,
        score: product.category.score,
        rate: product.category.rate,
        total: product.category.score * product.category.rate,
        owner_id: self.owner_id
      )
    end

    user = User.find(self.owner_id)
    user.score = total
    user.save!

    self.state =  ScheduledAgenda::STATE_QUALITY
    self.save!
  end
end

app/models/scheduled_agenda_score.rb
class ScheduledAgendaScore < ApplicationRecord
  belongs_to :scheduled_agenda
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable

  ROLE_ADMIN = 'admin'
  ROLE_USER = 'user'
  ROLE_MANANGER = 'mananger'

  enum role: [ROLE_ADMIN, ROLE_USER, ROLE_MANANGER]

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :name, presence: true

  def admin?
    self.role == ROLE_ADMIN
  end

  def user?
    self.role == ROLE_USER
  end

  def mananger?
    self.role == ROLE_MANANGER
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eco App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Eco App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <input type="checkbox" id="abrir-cerrar" name="abrir-cerrar" value="">
    <label for="abrir-cerrar">&#9776; <span class="abrir">Abrir</span><span class="cerrar">Cerrar</span></label>
    <div id="sidebar" class="sidebar">
        <ul class="menu">
            <li><a href="<%= scheduled_agendas_path %>">Agendar Cita 1</a></li>
            <li>
              <a href="<%= articles_path %>">
                <% if current_user.admin?() %>
                  <span class="item">Gestionar articulos</span>
                <% else %>
                  <span class="item">Tienda Virtual</span>
                <% end %>
              </a>
            </li>
            <% if current_user.admin? %>
              <li>
                <a href="<%= categories_path %>">Puntos x Categoria</a>
              </li>
              <li>
                <a href="<%= products_path %>">Productos</a>
              </li>
              <li><a href="<%= certificates_path %>">Certificar</a></li>
            <% end %>
            <li>
              <%= link_to "Cerrar session", destroy_user_session_path, method: :delete %>
            </li>
        </ul>
    </div>
    <div id="contenido">
      <div style=" margin-left: 100px; margin-top: 100px">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      <div>
    </div>
  </body>
</html>

app/views/shared/_left_sidebar.html.erb
<div class="wrapper">
  <div class="sidebar">
    <div class="profile">
      <img src="https://1.bp.blogspot.com/-vhmWFWO2r8U/YLjr2A57toI/AAAAAAAACO4/0GBonlEZPmAiQW4uvkCTm5LvlJVd_-l_wCNcBGAsYHQ/s16000/team-1-2.jpg" alt="profile_picture">
      <h3><%= current_user.name %></h3>
      <p> <%= current_user.role %></p>
    </div>
    <br/>
    <% if current_user.user?() %>
      <p style="color: white;">My score: <%= current_user.score %></p>
    <% end %>
    <br/>
    <br/>
    <ul>
      <li>
        <a href="<%= scheduled_agendas_path %>" class="active">
          <span class="item">Agendar Cita</span>
        </a>
      </li>

      <li>
        <a href="<%= articles_path %>">
          <% if current_user.admin?() %>
            <span class="item">Gestionar articulos</span>
          <% else %>
            <span class="item">Tienda Virtual</span>
          <% end %>
        </a>
      </li>

      <% if current_user.admin? %>
        <li>
            <a href="<%= categories_path %>">
              <span class="item">Puntos x Categoria</span>
            </a>
        </li>
        <li>
            <a href="<%= products_path %>">
              <span class="item">Productos</span>
            </a>
        </li>
        <li>
            <a href="<%= certificates_path %>">
              <span class="item">Certificar</span>
            </a>
        </li>
      <% end %>
      <li>
        <%= link_to "Cerrar session", destroy_user_session_path, method: :delete %>
      </li>
    </ul>
  </div>
</div>

<style media="screen">
  *{
    list-style: none;
    text-decoration: none;
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Open Sans', sans-serif;
  }

  body{
    background: #f5f6fa;
  }


  .wrapper .sidebar{
    background: rgb(5, 68, 104);
    position: fixed;
    top: 0;
    left: 0;
    width: 225px;
    height: 100%;
    padding: 20px 0;
    transition: all 0.5s ease;
  }

  .wrapper .sidebar .profile{
    margin-bottom: 30px;
    text-align: center;
  }

  .wrapper .sidebar .profile img{
    display: block;
    width: 100px;
    height: 100px;
    border-radius: 50%;
    margin: 0 auto;
  }

  .wrapper .sidebar .profile h3{
    color: #ffffff;
    margin: 10px 0 5px;
  }

  .wrapper .sidebar .profile p{
    color: rgb(206, 240, 253);
    font-size: 14px;
  }

  .wrapper .sidebar ul li a{
    display: block;
    padding: 13px 30px;
    border-bottom: 1px solid #10558d;
    color: rgb(241, 237, 237);
    font-size: 16px;
    position: relative;
  }

  .wrapper .sidebar ul li a .icon{
    color: #dee4ec;
    width: 30px;
    display: inline-block;
  }

  .wrapper .sidebar ul li a:hover,
  .wrapper .sidebar ul li a.active{
    color: #0c7db1;
    background:white;
    border-right: 2px solid rgb(5, 68, 104);
  }

  .wrapper .sidebar ul li a:hover .icon,
  .wrapper .sidebar ul li a.active .icon{
    color: #0c7db1;
  }

  .wrapper .sidebar ul li a:hover:before,
  .wrapper .sidebar ul li a.active:before{
    display: block;
  }

</style>